In [1]:
import pandas as pd
from bs4 import BeautifulSoup as bs
from splinter import Browser

In [2]:
url = "http://www.banxico.org.mx/apps/stdview.html?url=/apps/DAO-web/4/20/DistribucionTenencia.html"

In [3]:
executable_path = {"executable_path":"chromedriver.exe"}
browser = Browser("chrome",**executable_path,headless=False)

In [4]:
browser.visit(url)

In [5]:
html = browser.html

In [6]:
soup = bs(html,"html.parser")

In [7]:
table = soup.find("table",attrs={"border":"0","cellpadding":"5","cellspacing":"0","width":"80%","align":"center"})

In [8]:
tables = soup.find_all("table",attrs={"border":"0","cellpadding":"5","cellspacing":"0","width":"80%","align":"center"})

In [10]:
dict_list = []
for table in tables:
    table_data = table.find_all("tr")[1:]
    CI = []
    fechVenc = []
    repBanx = []
    garBanx = []
    vadBan = []
    Banca = []
    SSI = []
    Aseg = []
    Otros = []
    ResPai = []
    Ext = []
    Total = []
    
    import pdb; pdb.set_trace()
    
    for row in table_data:
        row_data = row.find_all("td")
        CI.append(row_data[0].text)
        fechVenc.append(row_data[1].text)
        repBanx.append(float(row_data[2].text.replace(",","")))
        garBanx.append(float(row_data[3].text.replace(",","")))
        vadBan.append(float(row_data[4].text.replace(",","")))
        Banca.append(float(row_data[5].text.replace(",","")))
        SSI.append(float(row_data[6].text.replace(",","")))
        Aseg.append(float(row_data[7].text.replace(",","")))
        Otros.append(float(row_data[8].text.replace(",","")))
        ResPai.append(float(row_data[9].text.replace(",","")))
        Ext.append(float(row_data[10].text.replace(",","")))
        Total.append(float(row_data[11].text.replace(",","")))
    
        table_dict = {
            "CI":CI,
            "Fecha de Vencimiento":fechVenc,
            "Garantías recibidas por Banxico":repBanx,
            "Valores adquiridos por Banxico":vadBan,
            "Sector Bancario":Banca,
            "Siefores y Sociedades de Inversión":SSI,
            "Aseguradoras y Afianzadoras":Aseg,
            "Otros Residentes en el Pais":ResPai,
            "Residentes en el Extranjero":Ext,
            "Total en Circulación":Total
        }
    
        dict_list.append(table_dict)

> <ipython-input-10-fd41bed65f98>(19)<module>()
-> for row in table_data:
(Pdb) row
<tr align="left"><td colspan="19">
</td></tr>
(Pdb) table
<table align="center" border="0" cellpadding="5" cellspacing="0" width="80%">
<tbody><tr class="banxicotabletitle">
<td align="center"> CI </td>
<td align="center">Fecha de Vencimiento</td>
<td align="center">Reportos con<br/>    Banxico<sup>2/</sup>    <br/>(a)</td>
<td align="center">Garantías recibidas<br/>por Banxico <sup>3/</sup><br/>(b)</td>
<td align="center">Valores adquiridos<br/>por Banxico<br/>(c)</td>
<td align="center">Sector Bancario<sup>4/</sup><br/>(d)</td>
<td align="center">Siefores y<br/>   Sociedades   <br/>de Inversión<br/>(e)</td>
<td align="center">  Aseguradoras  <br/>y Afianzadoras<br/>(f)</td>
<td align="center">Otros Residentes<br/>en el Pais<br/>(g)</td>
<td align="center">Residentes en el Pais<br/>  (I=a+b+c+d+e+f+g)  </td>
<td align="center">Residentes en el<br/>     Extranjero<sup>5/</sup>     <br/>(II)</td>
<td align="center">Total en<br/>Circulación<br/>(I + II)</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">23/05/2019</td>
<td align="right">   0.00</td>
<td align="right">3,544.43</td>
<td align="right">   0.00</td>
<td align="right">22,130.02</td>
<td align="right">45,412.08</td>
<td align="right">5,894.15</td>
<td align="right">37,898.99</td>
<td align="right"> 114,879.67</td>
<td align="right">24,030.31</td>
<td align="right"> 138,909.98</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">30/05/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 587.45</td>
<td align="right"> 606.77</td>
<td align="right"> 122.72</td>
<td align="right">9,275.66</td>
<td align="right">10,592.60</td>
<td align="right"> 741.58</td>
<td align="right">11,334.18</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">06/06/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,769.03</td>
<td align="right">13,328.64</td>
<td align="right"> 114.24</td>
<td align="right">12,287.99</td>
<td align="right">27,499.91</td>
<td align="right">7,767.64</td>
<td align="right">35,267.56</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">13/06/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,601.00</td>
<td align="right">   0.00</td>
<td align="right"> 111.00</td>
<td align="right">8,027.44</td>
<td align="right">9,739.44</td>
<td align="right">2,660.74</td>
<td align="right">12,400.18</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">20/06/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 833.24</td>
<td align="right">13,953.42</td>
<td align="right"> 840.18</td>
<td align="right">7,968.57</td>
<td align="right">23,595.41</td>
<td align="right">8,421.07</td>
<td align="right">32,016.48</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">27/06/2019</td>
<td align="right"> 139.55</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 293.61</td>
<td align="right">1,244.67</td>
<td align="right"> 399.19</td>
<td align="right">3,091.37</td>
<td align="right">5,168.39</td>
<td align="right">1,316.04</td>
<td align="right">6,484.43</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">04/07/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,108.58</td>
<td align="right">19,058.11</td>
<td align="right"> 274.20</td>
<td align="right">14,375.48</td>
<td align="right">36,816.37</td>
<td align="right">23,732.15</td>
<td align="right">60,548.52</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">11/07/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,797.42</td>
<td align="right"> 733.91</td>
<td align="right">   0.00</td>
<td align="right">5,339.13</td>
<td align="right">7,870.47</td>
<td align="right">  15.81</td>
<td align="right">7,886.28</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">18/07/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">6,695.64</td>
<td align="right">42,407.75</td>
<td align="right">1,687.95</td>
<td align="right">27,650.35</td>
<td align="right">78,441.69</td>
<td align="right">29,055.45</td>
<td align="right"> 107,497.15</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">25/07/2019</td>
<td align="right">   0.00</td>
<td align="right">  10.16</td>
<td align="right">   0.00</td>
<td align="right"> 152.76</td>
<td align="right">5,508.92</td>
<td align="right"> 400.00</td>
<td align="right">3,061.41</td>
<td align="right">9,133.25</td>
<td align="right">   5.84</td>
<td align="right">9,139.09</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">01/08/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">7,335.97</td>
<td align="right">5,164.16</td>
<td align="right"> 653.52</td>
<td align="right">13,589.48</td>
<td align="right">26,743.13</td>
<td align="right">14,294.52</td>
<td align="right">41,037.65</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">08/08/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,004.03</td>
<td align="right">3,000.00</td>
<td align="right">   0.00</td>
<td align="right">4,825.32</td>
<td align="right">8,829.36</td>
<td align="right">1,814.51</td>
<td align="right">10,643.86</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">15/08/2019</td>
<td align="right">   0.00</td>
<td align="right">  34.97</td>
<td align="right">   0.00</td>
<td align="right">3,268.63</td>
<td align="right">10,968.52</td>
<td align="right">  65.00</td>
<td align="right">10,913.11</td>
<td align="right">25,250.23</td>
<td align="right">10,595.38</td>
<td align="right">35,845.61</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">29/08/2019</td>
<td align="right"> 687.34</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 378.75</td>
<td align="right">6,731.70</td>
<td align="right"> 799.00</td>
<td align="right">14,130.39</td>
<td align="right">22,727.18</td>
<td align="right">5,389.75</td>
<td align="right">28,116.93</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">12/09/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">6,216.16</td>
<td align="right">11,689.38</td>
<td align="right">6,217.13</td>
<td align="right">11,493.07</td>
<td align="right">35,615.75</td>
<td align="right">18,985.32</td>
<td align="right">54,601.06</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">26/09/2019</td>
<td align="right"> 100.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,177.78</td>
<td align="right">14,569.92</td>
<td align="right">2,758.91</td>
<td align="right">9,468.15</td>
<td align="right">30,074.76</td>
<td align="right">4,687.05</td>
<td align="right">34,761.81</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">10/10/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">6,986.94</td>
<td align="right">3,769.23</td>
<td align="right">2,811.62</td>
<td align="right">8,609.41</td>
<td align="right">22,177.19</td>
<td align="right">3,300.98</td>
<td align="right">25,478.18</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">24/10/2019</td>
<td align="right">9,500.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,212.08</td>
<td align="right">8,321.84</td>
<td align="right"> 746.00</td>
<td align="right">6,411.55</td>
<td align="right">28,191.47</td>
<td align="right"> 100.80</td>
<td align="right">28,292.27</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">07/11/2019</td>
<td align="right"> 900.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,947.82</td>
<td align="right">13,188.55</td>
<td align="right">4,708.65</td>
<td align="right">11,156.33</td>
<td align="right">33,901.35</td>
<td align="right">30,175.48</td>
<td align="right">64,076.84</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">02/01/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">6,081.35</td>
<td align="right">19,932.81</td>
<td align="right">8,578.83</td>
<td align="right">9,191.79</td>
<td align="right">43,784.77</td>
<td align="right">22,604.65</td>
<td align="right">66,389.42</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">27/02/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">5,879.94</td>
<td align="right">9,251.76</td>
<td align="right">1,291.32</td>
<td align="right">1,616.26</td>
<td align="right">18,039.29</td>
<td align="right">25,210.76</td>
<td align="right">43,250.05</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">BI</td>
<td align="left">02/04/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,708.67</td>
<td align="right">5,994.34</td>
<td align="right">1,486.17</td>
<td align="right">1,362.78</td>
<td align="right">13,551.95</td>
<td align="right">15,831.20</td>
<td align="right">29,383.15</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">BI</td>
<td align="left">23/04/2020</td>
<td align="right">   0.00</td>
<td align="right"> 504.11</td>
<td align="right">   0.00</td>
<td align="right">3,049.38</td>
<td align="right">5,082.75</td>
<td align="right">2,453.17</td>
<td align="right">2,805.68</td>
<td align="right">13,895.08</td>
<td align="right"> 800.00</td>
<td align="right">14,695.08</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="center">-</td>
<td align="right">SUMA</td>
<td align="right">11,326.89</td>
<td align="right">4,093.67</td>
<td align="right">   0.00</td>
<td align="right">94,216.25</td>
<td align="right"> 259,919.25</td>
<td align="right">42,412.95</td>
<td align="right"> 234,549.69</td>
<td align="right"> 646,518.72</td>
<td align="right"> 251,537.02</td>
<td align="right"> 898,055.74</td>
</tr>
</tbody></table>

(Pdb) c
> <ipython-input-10-fd41bed65f98>(17)<module>()
-> import pdb; pdb.set_trace()
(Pdb) table
<table align="center" border="0" cellpadding="5" cellspacing="0" width="80%">
<tbody><tr class="banxicotabletitle">
<td align="center"> CI </td>
<td align="center">Fecha de Vencimiento</td>
<td align="center">Reportos con<br/>    Banxico<sup>2/</sup>    <br/>(a)</td>
<td align="center">Garantías recibidas<br/>por Banxico <sup>3/</sup><br/>(b)</td>
<td align="center">Valores adquiridos<br/>por Banxico<br/>(c)</td>
<td align="center">Sector Bancario<sup>4/</sup><br/>(d)</td>
<td align="center">Siefores y<br/>   Sociedades   <br/>de Inversión<br/>(e)</td>
<td align="center">  Aseguradoras  <br/>y Afianzadoras<br/>(f)</td>
<td align="center">Otros Residentes<br/>en el Pais<br/>(g)</td>
<td align="center">Residentes en el Pais<br/>  (I=a+b+c+d+e+f+g)  </td>
<td align="center">Residentes en el<br/>     Extranjero<sup>5/</sup>     <br/>(II)</td>
<td align="center">Total en<br/>Circulación<br/>(I + II)</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">06/06/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,180.47</td>
<td align="right">20,355.11</td>
<td align="right"> 871.12</td>
<td align="right">8,849.40</td>
<td align="right">34,256.10</td>
<td align="right">   3.14</td>
<td align="right">34,259.24</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">27/06/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,720.56</td>
<td align="right">25,292.31</td>
<td align="right"> 719.22</td>
<td align="right">7,449.75</td>
<td align="right">35,181.84</td>
<td align="right">   2.23</td>
<td align="right">35,184.07</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">01/08/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 170.68</td>
<td align="right">16,098.44</td>
<td align="right"> 500.74</td>
<td align="right">1,201.71</td>
<td align="right">17,971.57</td>
<td align="right">   0.00</td>
<td align="right">17,971.57</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">08/08/2019</td>
<td align="right">1,593.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,840.35</td>
<td align="right">30,057.66</td>
<td align="right">  90.00</td>
<td align="right">6,092.69</td>
<td align="right">39,673.71</td>
<td align="right">   0.00</td>
<td align="right">39,673.71</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">03/10/2019</td>
<td align="right"> 951.08</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 857.22</td>
<td align="right">22,917.35</td>
<td align="right"> 835.12</td>
<td align="right">11,396.36</td>
<td align="right">36,957.13</td>
<td align="right">   0.87</td>
<td align="right">36,958.00</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">24/10/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 662.61</td>
<td align="right">15,125.09</td>
<td align="right">  63.80</td>
<td align="right">2,119.47</td>
<td align="right">17,970.97</td>
<td align="right">   0.00</td>
<td align="right">17,970.97</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">05/12/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,702.32</td>
<td align="right">21,423.16</td>
<td align="right"> 237.59</td>
<td align="right">12,425.70</td>
<td align="right">36,788.77</td>
<td align="right">   0.00</td>
<td align="right">36,788.77</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">26/12/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 384.64</td>
<td align="right">37,494.20</td>
<td align="right">1,297.23</td>
<td align="right">3,457.92</td>
<td align="right">42,633.99</td>
<td align="right">   1.33</td>
<td align="right">42,635.32</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">16/01/2020</td>
<td align="right">1,389.06</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,080.81</td>
<td align="right">15,229.77</td>
<td align="right"> 142.04</td>
<td align="right">2,512.67</td>
<td align="right">20,354.36</td>
<td align="right">   0.00</td>
<td align="right">20,354.36</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">30/01/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,014.90</td>
<td align="right">31,780.35</td>
<td align="right"> 273.68</td>
<td align="right">7,179.04</td>
<td align="right">42,247.97</td>
<td align="right">   0.00</td>
<td align="right">42,247.97</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">02/04/2020</td>
<td align="right"> 908.11</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">7,250.33</td>
<td align="right">25,788.05</td>
<td align="right">1,671.65</td>
<td align="right">6,921.15</td>
<td align="right">42,539.28</td>
<td align="right">  30.00</td>
<td align="right">42,569.28</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">08/04/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 316.63</td>
<td align="right">9,178.93</td>
<td align="right">1,300.00</td>
<td align="right">6,490.69</td>
<td align="right">17,286.25</td>
<td align="right">  15.92</td>
<td align="right">17,302.17</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">28/05/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,245.18</td>
<td align="right">25,098.25</td>
<td align="right"> 161.28</td>
<td align="right">11,149.31</td>
<td align="right">40,654.02</td>
<td align="right">  12.90</td>
<td align="right">40,666.92</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">02/07/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,923.85</td>
<td align="right">17,823.43</td>
<td align="right">   0.00</td>
<td align="right">17,728.67</td>
<td align="right">38,475.95</td>
<td align="right">   0.00</td>
<td align="right">38,475.95</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">30/07/2020</td>
<td align="right">   0.00</td>
<td align="right"> 300.00</td>
<td align="right">   0.00</td>
<td align="right">6,625.89</td>
<td align="right">16,043.04</td>
<td align="right"> 593.63</td>
<td align="right">12,542.86</td>
<td align="right">36,105.43</td>
<td align="right">   0.00</td>
<td align="right">36,105.43</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">24/09/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,097.77</td>
<td align="right">15,250.11</td>
<td align="right">1,651.38</td>
<td align="right">22,077.65</td>
<td align="right">43,076.91</td>
<td align="right">   0.00</td>
<td align="right">43,076.91</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">26/11/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,459.69</td>
<td align="right">18,845.92</td>
<td align="right">1,399.86</td>
<td align="right">12,357.24</td>
<td align="right">35,062.71</td>
<td align="right">   0.00</td>
<td align="right">35,062.71</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">24/12/2020</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,385.58</td>
<td align="right">4,225.22</td>
<td align="right"> 166.00</td>
<td align="right">28,179.02</td>
<td align="right">34,955.82</td>
<td align="right"> 295.20</td>
<td align="right">35,251.03</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">21/01/2021</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">6,014.27</td>
<td align="right">14,528.64</td>
<td align="right">1,054.43</td>
<td align="right">14,500.09</td>
<td align="right">36,097.44</td>
<td align="right">   0.00</td>
<td align="right">36,097.44</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">25/03/2021</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,562.26</td>
<td align="right">7,763.32</td>
<td align="right"> 966.52</td>
<td align="right">21,763.07</td>
<td align="right">34,055.16</td>
<td align="right">   0.00</td>
<td align="right">34,055.16</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">20/05/2021</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,652.55</td>
<td align="right">6,765.34</td>
<td align="right">3,500.19</td>
<td align="right">24,504.27</td>
<td align="right">39,422.34</td>
<td align="right">   3.24</td>
<td align="right">39,425.58</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">27/05/2021</td>
<td align="right">4,000.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,342.86</td>
<td align="right">2,554.32</td>
<td align="right"> 981.09</td>
<td align="right">9,147.36</td>
<td align="right">18,025.63</td>
<td align="right">   0.00</td>
<td align="right">18,025.63</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">22/07/2021</td>
<td align="right"> 139.58</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,245.91</td>
<td align="right">9,940.24</td>
<td align="right"> 427.44</td>
<td align="right">6,284.39</td>
<td align="right">18,037.57</td>
<td align="right">  15.30</td>
<td align="right">18,052.87</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">19/08/2021</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,209.50</td>
<td align="right">9,712.93</td>
<td align="right">  16.00</td>
<td align="right">7,592.15</td>
<td align="right">20,530.58</td>
<td align="right">   9.46</td>
<td align="right">20,540.04</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">15/09/2021</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 480.26</td>
<td align="right">1,058.58</td>
<td align="right">   0.00</td>
<td align="right">17,253.01</td>
<td align="right">18,791.86</td>
<td align="right">  14.71</td>
<td align="right">18,806.57</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">18/11/2021</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,212.05</td>
<td align="right">19,663.79</td>
<td align="right"> 151.06</td>
<td align="right">18,620.83</td>
<td align="right">40,647.74</td>
<td align="right">   0.00</td>
<td align="right">40,647.74</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">13/01/2022</td>
<td align="right">2,366.79</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,495.93</td>
<td align="right">21,120.48</td>
<td align="right"> 364.76</td>
<td align="right">8,481.19</td>
<td align="right">34,829.14</td>
<td align="right">   0.00</td>
<td align="right">34,829.14</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">03/02/2022</td>
<td align="right">4,127.08</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">17,425.63</td>
<td align="right"> 260.05</td>
<td align="right">4,812.83</td>
<td align="right">26,625.59</td>
<td align="right">   2.86</td>
<td align="right">26,628.45</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">17/03/2022</td>
<td align="right">3,191.29</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,680.36</td>
<td align="right">11,200.01</td>
<td align="right">2,735.55</td>
<td align="right">17,223.20</td>
<td align="right">39,030.41</td>
<td align="right">   0.00</td>
<td align="right">39,030.41</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">28/04/2022</td>
<td align="right"> 951.57</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 949.90</td>
<td align="right"> 701.36</td>
<td align="right">   0.00</td>
<td align="right">1,900.52</td>
<td align="right">4,503.35</td>
<td align="right">   0.00</td>
<td align="right">4,503.35</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">12/05/2022</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 501.59</td>
<td align="right">21,361.14</td>
<td align="right">   0.00</td>
<td align="right">8,955.87</td>
<td align="right">30,818.60</td>
<td align="right">  18.72</td>
<td align="right">30,837.32</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">14/07/2022</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,716.70</td>
<td align="right">14,278.18</td>
<td align="right">   0.00</td>
<td align="right">11,070.52</td>
<td align="right">27,065.39</td>
<td align="right">   0.00</td>
<td align="right">27,065.39</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">08/09/2022</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">3,660.82</td>
<td align="right">13,941.79</td>
<td align="right"> 221.68</td>
<td align="right">14,508.20</td>
<td align="right">32,332.48</td>
<td align="right">   0.00</td>
<td align="right">32,332.48</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">10/11/2022</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 105.36</td>
<td align="right">16,264.82</td>
<td align="right">1,001.99</td>
<td align="right">10,445.05</td>
<td align="right">27,817.21</td>
<td align="right">   0.00</td>
<td align="right">27,817.21</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">05/01/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,496.52</td>
<td align="right">22,972.47</td>
<td align="right">   8.43</td>
<td align="right">7,915.88</td>
<td align="right">32,393.30</td>
<td align="right">   0.39</td>
<td align="right">32,393.69</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">09/03/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,303.89</td>
<td align="right">25,088.15</td>
<td align="right">1,621.39</td>
<td align="right">3,048.13</td>
<td align="right">31,061.56</td>
<td align="right">   0.00</td>
<td align="right">31,061.56</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">04/05/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,717.42</td>
<td align="right">23,331.39</td>
<td align="right">1,714.76</td>
<td align="right">8,803.16</td>
<td align="right">38,566.74</td>
<td align="right">   0.00</td>
<td align="right">38,566.74</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">06/07/2023</td>
<td align="right">7,000.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,050.87</td>
<td align="right">9,313.51</td>
<td align="right"> 563.18</td>
<td align="right">11,122.98</td>
<td align="right">32,050.55</td>
<td align="right">   0.00</td>
<td align="right">32,050.55</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">31/08/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,347.70</td>
<td align="right">25,827.94</td>
<td align="right">1,695.99</td>
<td align="right">4,706.16</td>
<td align="right">33,577.79</td>
<td align="right">   0.00</td>
<td align="right">33,577.79</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">01/11/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,901.78</td>
<td align="right">14,475.18</td>
<td align="right"> 450.31</td>
<td align="right">14,986.37</td>
<td align="right">32,813.63</td>
<td align="right">  40.04</td>
<td align="right">32,853.67</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">21/12/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,230.62</td>
<td align="right">14,385.90</td>
<td align="right">   0.00</td>
<td align="right">29,094.14</td>
<td align="right">47,710.67</td>
<td align="right">  33.18</td>
<td align="right">47,743.85</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">LD</td>
<td align="left">29/02/2024</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,462.73</td>
<td align="right">17,741.84</td>
<td align="right">   0.00</td>
<td align="right">27,909.21</td>
<td align="right">48,113.77</td>
<td align="right">   1.02</td>
<td align="right">48,114.80</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">LD</td>
<td align="left">25/04/2024</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 500.00</td>
<td align="right">5,666.79</td>
<td align="right"> 713.88</td>
<td align="right">3,621.85</td>
<td align="right">10,502.52</td>
<td align="right">  19.29</td>
<td align="right">10,521.81</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="center">-</td>
<td align="right">SUMA</td>
<td align="right">26,617.57</td>
<td align="right"> 300.00</td>
<td align="right">   0.00</td>
<td align="right"> 106,761.31</td>
<td align="right"> 715,110.15</td>
<td align="right">30,423.05</td>
<td align="right"> 488,401.70</td>
<td align="right">1,367,613.79</td>
<td align="right"> 519.80</td>
<td align="right">1,368,133.59</td>
</tr>
</tbody></table>

(Pdb) c
> <ipython-input-10-fd41bed65f98>(19)<module>()
-> for row in table_data:
(Pdb) table
<table align="center" border="0" cellpadding="5" cellspacing="0" width="80%">
<tbody><tr class="banxicotabletitle">
<td align="center"> CI </td>
<td align="center">Fecha de Vencimiento</td>
<td align="center">Reportos con<br/>    Banxico<sup>2/</sup>    <br/>(a)</td>
<td align="center">Garantías recibidas<br/>por Banxico <sup>3/</sup><br/>(b)</td>
<td align="center">Valores adquiridos<br/>por Banxico<br/>(c)</td>
<td align="center">Sector Bancario<sup>4/</sup><br/>(d)</td>
<td align="center">Siefores y<br/>   Sociedades   <br/>de Inversión<br/>(e)</td>
<td align="center">  Aseguradoras  <br/>y Afianzadoras<br/>(f)</td>
<td align="center">Otros Residentes<br/>en el Pais<br/>(g)</td>
<td align="center">Residentes en el Pais<br/>  (I=a+b+c+d+e+f+g)  </td>
<td align="center">Residentes en el<br/>     Extranjero<sup>5/</sup>     <br/>(II)</td>
<td align="center">Total en<br/>Circulación<br/>(I + II)</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">S </td>
<td align="left">13/06/2019</td>
<td align="right"> 122.08</td>
<td align="right">1,317.32</td>
<td align="right">   0.00</td>
<td align="right">3,051.65</td>
<td align="right">8,461.24</td>
<td align="right">2,447.61</td>
<td align="right">12,700.97</td>
<td align="right">28,100.87</td>
<td align="right">1,545.63</td>
<td align="right">29,646.49</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">S </td>
<td align="left">10/12/2020</td>
<td align="right"> 718.01</td>
<td align="right"> 393.14</td>
<td align="right">   0.00</td>
<td align="right">2,032.96</td>
<td align="right">23,160.86</td>
<td align="right">2,588.84</td>
<td align="right">6,127.19</td>
<td align="right">35,020.99</td>
<td align="right"> 751.29</td>
<td align="right">35,772.28</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">S </td>
<td align="left">09/06/2022</td>
<td align="right">   0.00</td>
<td align="right"> 371.58</td>
<td align="right">   0.00</td>
<td align="right"> 324.93</td>
<td align="right">25,766.00</td>
<td align="right">1,091.76</td>
<td align="right">5,888.45</td>
<td align="right">33,442.71</td>
<td align="right">3,610.33</td>
<td align="right">37,053.05</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">S </td>
<td align="left">04/12/2025</td>
<td align="right"> 155.00</td>
<td align="right">  37.36</td>
<td align="right">   0.00</td>
<td align="right">1,339.24</td>
<td align="right">33,712.04</td>
<td align="right">1,806.62</td>
<td align="right">4,162.11</td>
<td align="right">41,212.37</td>
<td align="right">1,000.33</td>
<td align="right">42,212.70</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">S </td>
<td align="left">30/11/2028</td>
<td align="right">   0.00</td>
<td align="right">   0.03</td>
<td align="right">   0.00</td>
<td align="right"> 939.79</td>
<td align="right">20,169.04</td>
<td align="right">1,349.78</td>
<td align="right">2,750.29</td>
<td align="right">25,208.94</td>
<td align="right"> 467.50</td>
<td align="right">25,676.44</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">S </td>
<td align="left">22/11/2035</td>
<td align="right">   0.00</td>
<td align="right">   0.18</td>
<td align="right">   0.00</td>
<td align="right"> 145.67</td>
<td align="right">13,065.24</td>
<td align="right">4,704.65</td>
<td align="right">3,917.55</td>
<td align="right">21,833.29</td>
<td align="right">1,284.34</td>
<td align="right">23,117.63</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">S </td>
<td align="left">15/11/2040</td>
<td align="right">   0.00</td>
<td align="right">  85.88</td>
<td align="right">   0.00</td>
<td align="right"> 554.24</td>
<td align="right">24,815.30</td>
<td align="right">12,223.83</td>
<td align="right">5,933.99</td>
<td align="right">43,613.24</td>
<td align="right">1,522.06</td>
<td align="right">45,135.30</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">S </td>
<td align="left">08/11/2046</td>
<td align="right">   0.00</td>
<td align="right">   0.11</td>
<td align="right">   0.00</td>
<td align="right"> 465.71</td>
<td align="right">8,165.62</td>
<td align="right">22,010.82</td>
<td align="right">7,107.84</td>
<td align="right">37,750.10</td>
<td align="right"> 817.99</td>
<td align="right">38,568.09</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="center">-</td>
<td align="right">SUMA</td>
<td align="right"> 995.09</td>
<td align="right">2,205.59</td>
<td align="right">   0.00</td>
<td align="right">8,854.19</td>
<td align="right"> 157,315.33</td>
<td align="right">48,223.91</td>
<td align="right">48,588.39</td>
<td align="right"> 266,182.51</td>
<td align="right">10,999.46</td>
<td align="right"> 277,181.97</td>
</tr>
</tbody></table>
(Pdb) c
> <ipython-input-10-fd41bed65f98>(17)<module>()
-> import pdb; pdb.set_trace()
(Pdb) table
<table align="center" border="0" cellpadding="5" cellspacing="0" width="80%">
<tbody><tr class="banxicotabletitle">
<td align="center"> CI </td>
<td align="center">Fecha de Vencimiento</td>
<td align="center">Reportos con<br/>    Banxico<sup>2/</sup>    <br/>(a)</td>
<td align="center">Garantías recibidas<br/>por Banxico <sup>3/</sup><br/>(b)</td>
<td align="center">Valores adquiridos<br/>por Banxico<br/>(c)</td>
<td align="center">Sector Bancario<sup>4/</sup><br/>(d)</td>
<td align="center">Siefores y<br/>   Sociedades   <br/>de Inversión<br/>(e)</td>
<td align="center">  Aseguradoras  <br/>y Afianzadoras<br/>(f)</td>
<td align="center">Otros Residentes<br/>en el Pais<br/>(g)</td>
<td align="center">Residentes en el Pais<br/>  (I=a+b+c+d+e+f+g)  </td>
<td align="center">Residentes en el<br/>     Extranjero<sup>5/</sup>     <br/>(II)</td>
<td align="center">Total en<br/>Circulación<br/>(I + II)</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">SP</td>
<td align="left">13/06/2019</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">  27.54</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">  27.54</td>
<td align="right">   0.00</td>
<td align="right">  27.54</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">SP</td>
<td align="left">04/12/2025</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">  16.08</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">  16.08</td>
<td align="right">   0.00</td>
<td align="right">  16.08</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">SP</td>
<td align="left">22/11/2035</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,852.58</td>
<td align="right">  96.38</td>
<td align="right">   0.00</td>
<td align="right">1,948.96</td>
<td align="right">   0.00</td>
<td align="right">1,948.96</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">SP</td>
<td align="left">15/11/2040</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 647.55</td>
<td align="right"> 721.44</td>
<td align="right">  31.50</td>
<td align="right">1,400.49</td>
<td align="right">   0.00</td>
<td align="right">1,400.49</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">SP</td>
<td align="left">08/11/2046</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,514.79</td>
<td align="right">  90.00</td>
<td align="right">1,604.79</td>
<td align="right">   0.00</td>
<td align="right">1,604.79</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="center">-</td>
<td align="right">SUMA</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">2,543.75</td>
<td align="right">2,332.61</td>
<td align="right"> 121.50</td>
<td align="right">4,997.86</td>
<td align="right">   0.00</td>
<td align="right">4,997.86</td>
</tr>
</tbody></table>

(Pdb) c
> <ipython-input-10-fd41bed65f98>(19)<module>()
-> for row in table_data:
(Pdb) table
<table align="center" border="0" cellpadding="5" cellspacing="0" width="80%">
<tbody><tr class="banxicotabletitle">
<td align="center"> CI </td>
<td align="center">Fecha de Vencimiento</td>
<td align="center">Reportos con<br/>    Banxico<sup>2/</sup>    <br/>(a)</td>
<td align="center">Garantías recibidas<br/>por Banxico <sup>3/</sup><br/>(b)</td>
<td align="center">Valores adquiridos<br/>por Banxico<br/>(c)</td>
<td align="center">Sector Bancario<sup>4/</sup><br/>(d)</td>
<td align="center">Siefores y<br/>   Sociedades   <br/>de Inversión<br/>(e)</td>
<td align="center">  Aseguradoras  <br/>y Afianzadoras<br/>(f)</td>
<td align="center">Otros Residentes<br/>en el Pais<br/>(g)</td>
<td align="center">Residentes en el Pais<br/>  (I=a+b+c+d+e+f+g)  </td>
<td align="center">Residentes en el<br/>     Extranjero<sup>5/</sup>     <br/>(II)</td>
<td align="center">Total en<br/>Circulación<br/>(I + II)</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">11/12/2019</td>
<td align="right">29,652.78</td>
<td align="right">9,388.57</td>
<td align="right">   0.00</td>
<td align="right">13,923.34</td>
<td align="right">24,353.97</td>
<td align="right">7,130.37</td>
<td align="right">19,688.84</td>
<td align="right"> 104,137.87</td>
<td align="right"> 104,778.31</td>
<td align="right"> 208,916.18</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">11/06/2020</td>
<td align="right">20,993.62</td>
<td align="right"> 238.49</td>
<td align="right">   0.00</td>
<td align="right">12,569.35</td>
<td align="right">12,471.07</td>
<td align="right">7,448.18</td>
<td align="right">85,926.49</td>
<td align="right"> 139,647.20</td>
<td align="right"> 133,130.22</td>
<td align="right"> 272,777.42</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">10/06/2021</td>
<td align="right">2,079.32</td>
<td align="right">8,919.52</td>
<td align="right">   0.00</td>
<td align="right">27,489.89</td>
<td align="right">35,446.34</td>
<td align="right">7,149.00</td>
<td align="right">37,155.48</td>
<td align="right"> 118,239.56</td>
<td align="right"> 156,634.09</td>
<td align="right"> 274,873.65</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">09/12/2021</td>
<td align="right">3,940.09</td>
<td align="right"> 770.56</td>
<td align="right">   0.00</td>
<td align="right">12,409.44</td>
<td align="right">28,578.36</td>
<td align="right">5,306.32</td>
<td align="right">44,201.84</td>
<td align="right">95,206.62</td>
<td align="right">88,188.28</td>
<td align="right"> 183,394.90</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">09/06/2022</td>
<td align="right">13,249.82</td>
<td align="right"> 101.21</td>
<td align="right">   0.00</td>
<td align="right">15,948.66</td>
<td align="right">36,733.79</td>
<td align="right">7,235.72</td>
<td align="right">26,810.91</td>
<td align="right"> 100,080.11</td>
<td align="right"> 164,152.73</td>
<td align="right"> 264,232.84</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">07/12/2023</td>
<td align="right">8,555.00</td>
<td align="right"> 100.00</td>
<td align="right">   0.00</td>
<td align="right">23,413.85</td>
<td align="right">45,439.31</td>
<td align="right">4,380.89</td>
<td align="right">21,253.07</td>
<td align="right"> 103,142.13</td>
<td align="right"> 137,864.05</td>
<td align="right"> 241,006.17</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">05/09/2024</td>
<td align="right">   0.00</td>
<td align="right"> 495.64</td>
<td align="right">   0.00</td>
<td align="right">9,276.12</td>
<td align="right">22,481.94</td>
<td align="right"> 325.04</td>
<td align="right">13,876.50</td>
<td align="right">46,455.23</td>
<td align="right">11,550.36</td>
<td align="right">58,005.58</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">05/12/2024</td>
<td align="right"> 769.18</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">9,795.36</td>
<td align="right">18,384.39</td>
<td align="right">8,289.20</td>
<td align="right">23,742.33</td>
<td align="right">60,980.46</td>
<td align="right"> 198,633.84</td>
<td align="right"> 259,614.29</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">05/03/2026</td>
<td align="right">   0.00</td>
<td align="right">2,852.55</td>
<td align="right">   0.00</td>
<td align="right">7,801.55</td>
<td align="right">39,655.36</td>
<td align="right">2,689.41</td>
<td align="right">9,456.12</td>
<td align="right">62,454.98</td>
<td align="right">97,466.32</td>
<td align="right"> 159,921.30</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">03/06/2027</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">10,546.74</td>
<td align="right">56,241.68</td>
<td align="right">4,420.23</td>
<td align="right">13,307.07</td>
<td align="right">84,515.73</td>
<td align="right"> 201,190.71</td>
<td align="right"> 285,706.44</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">31/05/2029</td>
<td align="right">   0.00</td>
<td align="right">1,972.18</td>
<td align="right">   0.00</td>
<td align="right">3,588.69</td>
<td align="right">40,191.37</td>
<td align="right">4,657.10</td>
<td align="right">14,564.36</td>
<td align="right">64,973.70</td>
<td align="right">93,568.87</td>
<td align="right"> 158,542.56</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">29/05/2031</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">4,210.25</td>
<td align="right">52,397.51</td>
<td align="right"> 231.29</td>
<td align="right">8,083.52</td>
<td align="right">64,922.57</td>
<td align="right">76,102.18</td>
<td align="right"> 141,024.75</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">23/11/2034</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">1,346.78</td>
<td align="right">46,503.22</td>
<td align="right">1,163.76</td>
<td align="right">5,406.12</td>
<td align="right">54,419.88</td>
<td align="right">36,181.45</td>
<td align="right">90,601.33</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">20/11/2036</td>
<td align="right">   0.00</td>
<td align="right"> 605.91</td>
<td align="right">   0.00</td>
<td align="right"> 225.05</td>
<td align="right">34,312.51</td>
<td align="right">1,236.09</td>
<td align="right">12,623.59</td>
<td align="right">49,003.15</td>
<td align="right">37,881.22</td>
<td align="right">86,884.37</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">18/11/2038</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 671.65</td>
<td align="right">30,411.79</td>
<td align="right">2,969.19</td>
<td align="right">10,242.98</td>
<td align="right">44,295.61</td>
<td align="right">89,929.07</td>
<td align="right"> 134,224.68</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">M </td>
<td align="left">13/11/2042</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right"> 131.84</td>
<td align="right">28,312.63</td>
<td align="right">1,368.55</td>
<td align="right">10,922.33</td>
<td align="right">40,735.35</td>
<td align="right"> 152,499.22</td>
<td align="right"> 193,234.58</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">M </td>
<td align="left">07/11/2047</td>
<td align="right">   0.00</td>
<td align="right">1,396.43</td>
<td align="right">   0.00</td>
<td align="right">1,059.87</td>
<td align="right">18,005.14</td>
<td align="right"> 864.15</td>
<td align="right">8,507.12</td>
<td align="right">29,832.71</td>
<td align="right">74,065.82</td>
<td align="right"> 103,898.53</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="center">-</td>
<td align="right">SUMA</td>
<td align="right">79,239.81</td>
<td align="right">26,841.05</td>
<td align="right">   0.00</td>
<td align="right"> 154,408.43</td>
<td align="right"> 569,920.38</td>
<td align="right">66,864.50</td>
<td align="right"> 365,768.68</td>
<td align="right">1,263,042.84</td>
<td align="right">1,853,816.74</td>
<td align="right">3,116,859.58</td>
</tr>
</tbody></table>

(Pdb) c
> <ipython-input-10-fd41bed65f98>(17)<module>()
-> import pdb; pdb.set_trace()
(Pdb) table
<table align="center" border="0" cellpadding="5" cellspacing="0" width="80%">
<tbody><tr class="banxicotabletitle">
<td align="center"> CI </td>
<td align="center">Fecha de Vencimiento</td>
<td align="center">Reportos con<br/>    Banxico<sup>2/</sup>    <br/>(a)</td>
<td align="center">Garantías recibidas<br/>por Banxico <sup>3/</sup><br/>(b)</td>
<td align="center">Valores adquiridos<br/>por Banxico<br/>(c)</td>
<td align="center">Sector Bancario<sup>4/</sup><br/>(d)</td>
<td align="center">Siefores y<br/>   Sociedades   <br/>de Inversión<br/>(e)</td>
<td align="center">  Aseguradoras  <br/>y Afianzadoras<br/>(f)</td>
<td align="center">Otros Residentes<br/>en el Pais<br/>(g)</td>
<td align="center">Residentes en el Pais<br/>  (I=a+b+c+d+e+f+g)  </td>
<td align="center">Residentes en el<br/>     Extranjero<sup>5/</sup>     <br/>(II)</td>
<td align="center">Total en<br/>Circulación<br/>(I + II)</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">MP</td>
<td align="left">07/12/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">  55.08</td>
<td align="right">   0.00</td>
<td align="right">  61.10</td>
<td align="right"> 116.18</td>
<td align="right">   6.18</td>
<td align="right"> 122.36</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="left">MP</td>
<td align="left">05/12/2024</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.02</td>
<td align="right">1,757.04</td>
<td align="right">   0.00</td>
<td align="right">1,863.19</td>
<td align="right">3,620.25</td>
<td align="right">   3.87</td>
<td align="right">3,624.12</td>
</tr>
<tr align="left" class="banxicotablerow1">
<td align="left">MP</td>
<td align="left">03/06/2027</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.10</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.10</td>
<td align="right">   0.00</td>
<td align="right">   0.10</td>
</tr>
<tr align="left" class="banxicotablerow2">
<td align="center">-</td>
<td align="right">SUMA</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.02</td>
<td align="right">1,812.22</td>
<td align="right">   0.00</td>
<td align="right">1,924.29</td>
<td align="right">3,736.52</td>
<td align="right">  10.05</td>
<td align="right">3,746.57</td>
</tr>
<tr align="left"><td colspan="19">
</td></tr></tbody></table>
(Pdb) n
> <ipython-input-10-fd41bed65f98>(19)<module>()
-> for row in table_data:
(Pdb) n
> <ipython-input-10-fd41bed65f98>(20)<module>()
-> row_data = row.find_all("td")
(Pdb) row
<tr align="left" class="banxicotablerow1">
<td align="left">MP</td>
<td align="left">07/12/2023</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">   0.00</td>
<td align="right">  55.08</td>
<td align="right">   0.00</td>
<td align="right">  61.10</td>
<td align="right"> 116.18</td>
<td align="right">   6.18</td>
<td align="right"> 122.36</td>
</tr>
(Pdb) n
> <ipython-input-10-fd41bed65f98>(21)<module>()
-> CI.append(row_data[0].text)
(Pdb) row_data
[<td align="left">MP</td>, <td align="left">07/12/2023</td>, <td align="right">   0.00</td>, <td align="right">   0.00</td>, <td align="right">   0.00</td>, <td align="right">   0.00</td>, <td align="right">  55.08</td>, <td align="right">   0.00</td>, <td align="right">  61.10</td>, <td align="right"> 116.18</td>, <td align="right">   6.18</td>, <td align="right"> 122.36</td>]
(Pdb) row_data[0]
<td align="left">MP</td>
(Pdb) row_data[0].text
'MP'
(Pdb) c

IndexError: list index out of range

In [24]:
table_data = table.find_all("tr")[1:]

In [52]:
CI = []
fechVenc = []
repBanx = []
garBanx = []
vadBan = []
Banca = []
SSI = []
Aseg = []
Otros = []
ResPai = []
Ext = []
Total = []

In [53]:
for row in table_data:
    row_data = row.find_all("td")
    CI.append(row_data[0].text)
    fechVenc.append(row_data[1].text)
    repBanx.append(float(row_data[2].text.replace(",","")))
    garBanx.append(float(row_data[3].text.replace(",","")))
    vadBan.append(float(row_data[4].text.replace(",","")))
    Banca.append(float(row_data[5].text.replace(",","")))
    SSI.append(float(row_data[6].text.replace(",","")))
    Aseg.append(float(row_data[7].text.replace(",","")))
    Otros.append(float(row_data[8].text.replace(",","")))
    ResPai.append(float(row_data[9].text.replace(",","")))
    Ext.append(float(row_data[10].text.replace(",","")))
    Total.append(float(row_data[11].text.replace(",","")))

In [54]:
cetes_dict = {
    "CI":CI,
    "Fecha de Vencimiento":fechVenc,
    "Garantías recibidas por Banxico":repBanx,
    "Valores adquiridos por Banxico":vadBan,
    "Sector Bancario":Banca,
    "Siefores y Sociedades de Inversión":SSI,
    "Aseguradoras y Afianzadoras":Aseg,
    "Otros Residentes en el Pais":ResPai,
    "Residentes en el Extranjero":Ext,
    "Total en Circulación":Total
}

In [57]:
df = pd.DataFrame(cetes_dict)

In [58]:
df

,CI,Fecha de Vencimiento,Garantías recibidas por Banxico,Valores adquiridos por Banxico,Sector Bancario,Siefores y Sociedades de Inversión,Aseguradoras y Afianzadoras,Otros Residentes en el Pais,Residentes en el Extranjero,Total en Circulación
0,BI,23/05/2019,0.00,0.0,22130.02,45412.08,5894.15,114879.67,24030.31,138909.98
1,BI,30/05/2019,0.00,0.0,587.45,606.77,122.72,10592.60,741.58,11334.18
2,BI,06/06/2019,0.00,0.0,1769.03,13328.64,114.24,27499.91,7767.64,35267.56
3,BI,13/06/2019,0.00,0.0,1601.00,0.00,111.00,9739.44,2660.74,12400.18
4,BI,20/06/2019,0.00,0.0,833.24,13953.42,840.18,23595.41,8421.07,32016.48
5,BI,27/06/2019,139.55,0.0,293.61,1244.67,399.19,5168.39,1316.04,6484.43
6,BI,04/07/2019,0.00,0.0,3108.58,19058.11,274.20,36816.37,23732.15,60548.52
7,BI,11/07/2019,0.00,0.0,1797.42,733.91,0.00,7870.47,15.81,7886.28
8,BI,18/07/2019,0.00,0.0,6695.64,42407.75,1687.95,78441.69,29055.45,107497.15
9,BI,25/07/2019,0.00,0.0,152.76,5508.92,400.00,9133.25,5.84,9139.09
10,BI,01/08/2019,0.00,0.0,7335.97,5164.16,653.52,26743.13,14294.52,41037.65
11,BI,08/08/2019,0.00,0.0,1004.03,3000.00,0.00,8829.36,1814.51,10643.86
12,BI,15/08/2019,0.00,0.0,3268.63,10968.52,65.00,25250.23,10595.38,35845.61
13,BI,29/08/2019,687.34,0.0,378.75,6731.70,799.00,22727.18,5389.75,28116.93
14,BI,12/09/2019,0.00,0.0,6216.16,11689.38,6217.13,35615.75,18985.32,54601.06
15,BI,26/09/2019,100.00,0.0,3177.78,14569.92,2758.91,30074.76,4687.05,34761.81
16,BI,10/10/2019,0.00,0.0,6986.94,3769.23,2811.62,22177.19,3300.98,25478.18
17,BI,24/10/2019,9500.00,0.0,3212.08,8321.84,746.00,28191.47,100.80,28292.27
18,BI,07/11/2019,900.00,0.0,3947.82,13188.55,4708.65,33901.35,30175.48,64076.84
19,BI,02/01/2020,0.00,0.0,6081.35,19932.81,8578.83,43784.77,22604.65,66389.42
20,BI,27/02/2020,0.00,0.0,5879.94,9251.76,1291.32,18039.29,25210.76,43250.05
21,BI,02/04/2020,0.00,0.0,4708.67,5994.34,1486.17,13551.95,15831.20,29383.15
22,BI,23/04/2020,0.00,0.0,3049.38,5082.75,2453.17,13895.08,800.00,14695.08
23,-,SUMA,11326.89,0.0,94216.25,259919.25,42412.95,646518.72,251537.02,898055.74